### ISSUE TITLE
A2A DID Mapping Provider

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/did-comm-go#11]
New provider to store/map the agent DIDs along verkeys in a A2A relationship.

**Comment by llorllale** [comment]
@rolsonquadras trying to understand this....

Is the purpose here to keep track of what pairwise DIDs were exchanged in each of the Agent's relationships?

**Comment by rolsonquadras** [comment]
> @rolsonquadras trying to understand this
> 
> Is the purpose here to keep track of what pairwise DIDs were exchanged in each of the Agent's relationships?

@llorllale exactly

**Comment by llorllale** [comment]
@rolsonquadras would be great to add that explanation to this issue's description :)....

**Comment by llorllale** [comment]
@rolsonquadras also, I'm not clear why this library should provide this feature. From the explanation above, sounds like it belongs more to the Agent framework.

The Agent should probably be passing in an implementation that handles this mapping for the didcomm layer. WDYT?

**Comment by rolsonquadras** [comment]
> @rolsonquadras would be great to add that explanation to this issue's description :)

My bad. I had updated in the PR. Missed to add here.

**Comment by rolsonquadras** [comment]
> @rolsonquadras also, I'm not clear why this library should provide this feature. From the explanation above, sounds like it belongs more to the Agent framework.
> 
> The Agent should probably be passing in an implementation that handles this mapping for the didcomm layer. WDYT?

@llorllale  Yeah, we will have option to inject it to did-comm. But did-comm will provide basic implementation.

**Comment by llorllale** [comment]
@rolsonquadras I don't see why didcomm needs to provide even a basic implementation for this.

cc: @troyronda @Baha-sk

**Comment by rolsonquadras** [comment]
@llorllale Agreed. Closing this issue and related PR #12
