### ISSUE TITLE
Generate Communication Invitation

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/did-comm-go#13]
DIDComm generates the connection invitation and it's upto Agent to share it (it could be through HTTP, QR Code, Bluetooth).

**Comment by llorllale** [comment]
@rolsonquadras was this not the transport layer that @Baha-sk was working on?

**Comment by llorllale** [comment]
@rolsonquadras I'm having trouble understanding the overall design we're going for here. Can you provide a quick code snippet showing more or less what in the end a client will have to do did-exchange?

**Comment by rolsonquadras** [comment]
@llorllale We need to refactor that. DID Comm should just generate the invitation (based on the spec). It will be upto agents to share the info (for now, agent-framework will send the invitation through http). 

Adding @troyronda to conversation.

**Comment by llorllale** [comment]
@rolsonquadras code snippet?

Will it look like this maybe?

```go
type Transport interface {
    Send(msg interface{}) error    // I'm not sure what type msg should be...
}

func main() {
    invite, err := invite.Generate(id, did, label)
    transport, err := http.NewTransport(config interface{})
    transport.send(invite)
}
```

**Comment by rolsonquadras** [comment]
> @rolsonquadras code snippet?
> 
> Will it look like this maybe?
> 
> ```go
> type Transport interface {
>     Send(msg interface{}) error    // I'm not sure what type msg should be...
> }
> 
> func main() {
>     invite, err := invite.Generate(id, did, label, signer)
>     transport, err := http.NewTransport(config interface{})
>     transport.send(invite)
> }
> ```

@llorllale Agent can share the invitation(flow #0 message) in any way it want(http/QR/bluetooth etc). We shouldn't have the the sharing/transport logic for this message flow in did-comm-go lib.

**Comment by llorllale** [comment]
@rolsonquadras ok, gotcha - this ticket specifically deals with the [invitation to exchange](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#0-invitation-to-exchange)

I recommend updating this issue's title and description to say "invitation to exchange message" as opposed to "communication invitation". It would make it a lot more clearer what we're referring to.

**Comment by rolsonquadras** [comment]
> @rolsonquadras ok, gotcha - this ticket specifically deals with the [invitation to exchange](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#0-invitation-to-exchange)
> 
> I recommend updating this issue's title and description to say "invitation to exchange message" as opposed to "communication invitation". It would make it a lot more clearer what we're referring to.

@llorllale perhaps I could have added the link.

**Comment by llorllale** [comment]
Substituting "connection invitation" with "invitation to exchange" will do
